name: teambeat
region: nyc

# Pre-deploy job to run database migrations
jobs:
  - name: db-migrate
    kind: PRE_DEPLOY
    dockerfile_path: Dockerfile
    source_dir: /
    run_command: ./scripts/migrate.sh
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET

# Main web service
services:
  - name: web
    dockerfile_path: Dockerfile
    source_dir: /
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs

    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3

    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: SKIP_MIGRATION
        value: "true"
      # Sentry configuration (optional)
      # Uncomment and add values in Digital Ocean dashboard if using Sentry
      # - key: SENTRY_DSN
      #   scope: RUN_TIME
      #   type: SECRET
      # - key: PUBLIC_SENTRY_DSN
      #   scope: BUILD_AND_RUN_TIME
      #   type: SECRET
      # - key: SENTRY_AUTH_TOKEN
      #   scope: BUILD_TIME
      #   type: SECRET

    routes:
      - path: /
